Repository navikt/mock-oauth2-server, pull requests merged in 2022-03, with the labels that each got.

#203 feat: support deployment on Heroku
  README.md
  src/main/kotlin/no/nav/security/mock/oauth2/StandaloneMockOAuth2Server.kt
  src/test/kotlin/no/nav/security/mock/oauth2/StandaloneMockOAuth2ServerKtTest.kt
Labels: enhancement

#199 feature: add support for request/response interceptors, support CORS with credentials
  src/main/kotlin/no/nav/security/mock/oauth2/http/CorsInterceptor.kt
  src/main/kotlin/no/nav/security/mock/oauth2/http/OAuth2HttpRequestHandler.kt
  src/main/kotlin/no/nav/security/mock/oauth2/http/OAuth2HttpResponse.kt
  src/main/kotlin/no/nav/security/mock/oauth2/http/OAuth2HttpRouter.kt
  src/test/kotlin/examples/kotlin/ktor/client/OAuth2Client.kt
  src/test/kotlin/no/nav/security/mock/oauth2/e2e/CorsHeadersIntegrationTest.kt
  src/test/kotlin/no/nav/security/mock/oauth2/http/OAuth2HttpRouterTest.kt
  src/test/kotlin/no/nav/security/mock/oauth2/testutils/Http.kt
Labels: enhancement, security findings

#223 Fix issue with host header and port handling
  src/main/kotlin/no/nav/security/mock/oauth2/http/OAuth2HttpRequest.kt
  src/test/kotlin/no/nav/security/mock/oauth2/http/OAuth2HttpRequestTest.kt
Labels: bug
